package by.custom.utilcalculator.domain.constants.steps;

public enum SelfPropelledType implements StepsIndicator {
    GRADER,
    BULLDOZER,
    EXCAVATOR,
    WHEEL_LOADER,
    TAMPING_MACHINE,
    FRONT_LOADER,
    WHEELED_CRANES,
    PIPELAYERS,
    TRAILERS_OTHER,
    ROAD_MAINTENANCE,
    FORESTRY,
    FORWADERS,
    TIMBER_LOADERS,
    WHEELED_TRACTORS,
    CRAWLER_TRACTORS,
    COMBINE_HARVESTERS,
    FORAGE_HARVESTERS,
    AGRICULTURAL_VEHICLES,
    OFF_ROAD_DUMP_TRUCKS
}
