package by.custom.utilcalculator.domain.constants.steps;

public enum Step {
    GENERAL_TRANSPORT_TYPE, COUNTRY_ORIGIN, EXCEPT_M1_TRANSPORT_TYPE, OWNERS_TYPE, N1_N3_WEIGHT, TYPE_OF_ENGINE, VOLUME_OF_ENGINE, CAR_AGE, FAREWELL
}
